# Generated by Django 3.0.11 on 2021-01-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsa_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
            ],
        ),
    ]
