# Generated by Django 3.0.11 on 2021-01-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsa_web', '0002_secretmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretmessage',
            name='author',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='secretmessage',
            name='title',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
