# Generated by Django 3.0.11 on 2021-01-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsa_web', '0003_auto_20210104_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretmessage',
            name='author',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='secretmessage',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
