# Generated by Django 3.0.11 on 2021-01-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsa_web', '0004_auto_20210104_1133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecretMessage',
        ),
    ]
