# Generated by Django 3.0.11 on 2021-01-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsa_web', '0006_secretmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretmessage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='secretmessage',
            name='title',
        ),
    ]
